services:
  direlera:
    image: ghcr.io/caromdreamer/direlera-rs:latest
    container_name: direlera
    restart: always
    pull_policy: always
    ports:
      - "8080:8080/udp"
      - "27888:27888/udp"
      - "9091:9091"
    volumes:
      - ./config.toml:/app/config.toml:ro
